package com.menglang.crm.mapper;

import com.menglang.crm.pojo.CustomerLinkman;
import com.menglang.crm.pojo.CustomerLinkmanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    int countByExample(CustomerLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    int deleteByExample(CustomerLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    int insert(CustomerLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    int insertSelective(CustomerLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    List<CustomerLinkman> selectByExample(CustomerLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    CustomerLinkman selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") CustomerLinkman record, @Param("example") CustomerLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    int updateByExample(@Param("record") CustomerLinkman record, @Param("example") CustomerLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    int updateByPrimaryKeySelective(CustomerLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbggenerated Thu Oct 26 10:53:56 CST 2017
     */
    int updateByPrimaryKey(CustomerLinkman record);
}